//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 PlayerNew.rc 使用
//
#define IDC_BT_COPYABOUT                2
#define IDD_ABOUT                       101
#define IDR_PNBIN1                      132
#define IDR_BIN_COMPILECOUNT            132
#define IDR_BIN_COMPILETIME             133
#define IDI_ICON1                       136
#define IDI_MAIN                        136
#define IDD_EQ                          179
#define IDD_EFFECT                      190
#define IDD_SBV                         191
#define IDD_FXCOMM                      191
#define IDD_INPUT                       192
#define IDD_OPTIONS                     200
#define IDD_OPTIONS2                    201
#define IDD_OPTLRC                      201
#define IDD_123                         202
#define IDD_CHORUS                      203
#define IDD_COMPRESSOR                  204
#define IDD_DISTORTION                  205
#define IDD_ECHO                        206
#define IDD_FLANGER                     207
#define IDD_GARGLE                      208
#define IDD_I3DL2REVERB                 209
#define IDD_REVERB                      210
#define IDD_ROTATE                      251
#define IDD_OPTPLAYING                  256
#define IDD_OPTVISUAL                   257
#define IDD_OPTHOTKEY                   258
#define IDC_LIST1                       1002
#define IDC_LB_FXPRIORITY               1002
#define IDC_BUTTON1                     1003
#define IDC_LK_AUTHOR                   1004
#define IDC_LK_3RDPARTYLIB              1005
#define IDC_ST_COMPILETIME              1006
#define IDC_ST_COMPILECOUNT             1007
#define IDC_ST_BASSVER                  1008
#define IDC_LK_OPENGITHUB               1009
#define IDC_RB_QUADWAVE                 1009
#define IDC_ST_PNVER                    1010
#define IDC_ST_TEMPOTIP                 1015
#define IDC_ST_SPEEDTIP                 1016
#define IDC_ST_PANTIP                   1017
#define IDC_ST_PITCHTIP                 1018
#define IDOK2                           1032
#define IDC_BT_CANCEL                   1034
#define IDC_BT_OK                       1036
#define IDC_ST_TIP                      1037
#define IDC_LV_LISTFILE                 1038
#define IDC_BT_GITHUB                   1038
#define IDC_ST_MAINICON                 1040
#define IDC_TB_BANDWIDTH                1045
#define IDC_CB_EQ                       1046
#define IDC_BT_RESET                    1047
#define IDC_TB2                         1048
#define IDC_TB1                         1049
#define IDC_TB3                         1050
#define IDC_TB5                         1051
#define IDC_TB4                         1052
#define IDC_TB7                         1053
#define IDC_TB6                         1054
#define IDC_TB9                         1055
#define IDC_TB8                         1056
#define IDC_TB10                        1057
#define IDC_CM                          1059
#define IDC_TAB                         1060
#define IDC_TAB_EFFECT                  1060
#define IDC_TB_SPEED                    1061
#define IDC_TB_VOL                      1062
#define IDC_TB_BLANCE                   1063
#define IDC_TB_PAN                      1063
#define IDC_ST_SPEED                    1064
#define IDC_ST_BLANCE                   1065
#define IDC_TB_PITCH                    1065
#define IDC_ST_SPEED2                   1066
#define IDC_ST_VU                       1067
#define IDC_BT_VOL                      1068
#define IDC_ST_BLANCE2                  1069
#define IDC_ED_INPUT                    1069
#define IDC_ST_PAN                      1069
#define IDC_ST_VOL2                     1070
#define IDC_ST_INPUT                    1070
#define IDC_ST_VOL                      1070
#define IDC_ST_ABOUT                    1071
#define IDC_TB_TEMPO                    1071
#define IDC_ST_TEMPO                    1072
#define IDC_ED_BMNAME                   1073
#define IDC_ST_TEMPO2                   1073
#define IDC_ST_PITCH                    1073
#define IDC_ED_BMCOMMENT                1074
#define IDC_ST_TEMPO3                   1074
#define IDC_ED_BMINDEX                  1075
#define IDC_ED_BMCLR                    1076
#define IDC_BT_BMSAVE                   1077
#define IDC_BT_BMJUMP                   1078
#define IDC_BT_BMDEL                    1079
#define IDC_ST_BMCLR                    1081
#define IDC_ST_DAYLYTIP                 1082
#define IDC_SB_SETTINGS                 1083
#define IDC_CB_DEFTEXTCODE              1086
#define IDC_CB_SCLRCALIGN               1087
#define IDC_CB_DISABLEVANIMATION        1088
#define IDC_CB_DISABLEWORDBREAK         1089
#define IDC_CB_DISABLEDTLRCSHANDOW      1090
#define IDC_CB_ENABLEDTLRCBORDER        1091
#define IDC_ED_LRCDIR                   1092
#define IDC_BT_CHANGELRCDIR             1093
#define IDC_ED_LRCDIR2                  1094
#define IDC_ED_DTLRCSPACELINE           1094
#define IDC_BT_CHANGEFONT               1095
#define IDC_ED_DTLRCFONTINFO            1096
#define IDC_BT_CHANGEFONT2              1097
#define IDC_ED_SCLRCFONTINFO            1098
#define IDC_TB_DTLRCTRANSPARENT         1099
#define IDC_ED_ALBUMPICSIZE2            1099
#define IDC_ST_DTLRCCLR1                1100
#define IDC_ST_DTLRCCLR2                1101
#define IDC_TB_REVERBMIX                1102
#define IDC_ST_SCLRCCLR1                1102
#define IDC_ST_SCLRCCLR2                1103
#define IDC_RB_SINEWAVE                 1104
#define IDC_TB_REVERBDELAY              1104
#define IDC_ST_DTLRCBORDERCLR           1104
#define IDC_RB_TRIANGLEWAVE             1105
#define IDC_TB_REFLECTIONSDELAY         1105
#define IDC_ED_SCLRCLINEGAP             1105
#define IDC_TB_REVERB                   1106
#define IDC_TB_REVERBTIME               1106
#define IDC_ED_SCLRCALIGNOFFSET         1106
#define IDC_TB_HIGHFREQRTRATIO          1107
#define IDC_CB_DTLINE                   1107
#define IDC_TB_DECAYHFRADIO             1108
#define IDC_BT_CHANGEFONT3              1108
#define IDC_TB_DECAYTIME                1109
#define IDC_ED_DTLRCFONTINFO2           1109
#define IDC_CB_LFOPHASE                 1110
#define IDC_TB_DIFFUSION                1110
#define IDC_ST_DTLRCCLRHIGHLIGHT1       1110
#define IDC_CB_PANDELAY                 1111
#define IDC_ST_DTLRCCLRHIGHLIGHT2       1111
#define IDC_TB_WETDRYMIX                1112
#define IDC_TB_DENSITY                  1112
#define IDC_CB_DTLRCALIGN1              1112
#define IDC_TB_LFODEPTH                 1113
#define IDC_TB_HFREFERENCE              1113
#define IDC_CB_DTLRCALIGN2              1113
#define IDC_TB_FEEDBACK                 1114
#define IDC_CB_DISABLESCLRC             1114
#define IDC_TB_LFOFREQUENCY             1115
#define IDC_CB_DISABLEVANIMATION3       1115
#define IDC_TB_DELAY                    1116
#define IDC_CB_ENABLE                   1117
#define IDC_TB_GAIN                     1118
#define IDC_TB_ATTACK                   1119
#define IDC_TB_RELEASE                  1120
#define IDC_TB_THRESHOLD                1121
#define IDC_TB_RATIO                    1122
#define IDC_TB_PREDELAY                 1123
#define IDC_TB_EDGE                     1124
#define IDC_TB_CENTERFREQUENCY          1125
#define IDC_TB_PRELOWPASSCUTOFF         1126
#define IDC_TB_LEFTDELAY                1127
#define IDC_TB_RIGHTDELAY               1128
#define IDC_TB_RATEHZ                   1129
#define IDC_TB_ROOM                     1130
#define IDC_TB_ROOMHF                   1131
#define IDC_TB_ROOMROLLOFFFACTOR        1132
#define IDC_TB_REFLECTIONS              1133
#define IDC_BT_REFRESHDEV               1135
#define IDC_CB_DEVICES                  1138
#define IDC_LB_OPTIONS                  1152
#define IDC_CB_HSCROLLTEXT              1154
#define IDC_CB_VISUAL                   1155
#define IDC_ED_ALBUMPICSIZE1            1156
#define IDC_ED_SOUNDFONT                1157
#define IDC_BT_CHANGESOUNDFONT          1158
#define IDC_LV_STATARTISTS              1159
#define IDC_RB_STATMONTH                1160
#define IDC_RB_STATYEAR                 1161
#define IDC_LV_STATSONGS                1162
#define IDC_BT_REFRESHSTAT              1163
#define IDC_LV_STATSONGS2               1164
#define IDC_BT_BACKTOSTAT               1165
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1019
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
